"""add preview & description

Revision ID: 5367c5343ed1
Revises: 71dc6a361d33
Create Date: 2025-05-23 19:30:43.947353

"""
from alembic import op
import sqlalchemy as sa
import fastapi_storages


# revision identifiers, used by Alembic.
revision = '5367c5343ed1'
down_revision = '71dc6a361d33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('preview', fastapi_storages.integrations.sqlalchemy.ImageType(storage=fastapi_storages.FileSystemStorage("storage")), nullable=True))
    op.add_column('lessons', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'description')
    op.drop_column('lessons', 'preview')
    # ### end Alembic commands ###
