"""add text file

Revision ID: e50be3206ad6
Revises: 5367c5343ed1
Create Date: 2025-05-23 20:15:13.773920

"""

from alembic import op
import sqlalchemy as sa
import fastapi_storages


# revision identifiers, used by Alembic.
revision = "e50be3206ad6"
down_revision = "5367c5343ed1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lessons",
        sa.Column(
            "text_file",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=fastapi_storages.FileSystemStorage("storage")
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lessons", "text_file")
    # ### end Alembic commands ###
